create table book (
	id INT,
	book_title VARCHAR(50),
	author VARCHAR(50),
	genre VARCHAR(50),
	total_copies INT,
	available_copies INT,
	date_acquired DATE,
	price DECIMAL(5,2)
);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (83, 'Evelyn', 'Allina Stoeckle', 'Drama', 22, 20, '10/28/2014', 18.96);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (21, 'Harry Potter and the Chamber of Secrets', 'Verna Stidston', 'Adventure|Fantasy', 16, 2, '10/2/2002', 46.0);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (26, 'Prince of Central Park, The', 'Rina Strafford', 'Action|Adventure|Drama', 28, 10, '12/30/2006', 99.68);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (31, 'Life with Father', 'Lucille Punton', 'Comedy', 34, 15, '9/18/2022', 42.83);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (47, 'Regeneration', 'Bride Jemmett', 'Crime|Drama|Romance', 33, 14, '8/11/2023', 39.38);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (16, 'What to Do in Case of Fire (Was tun, wenn''s brennt?)', 'Anatole Ind', 'Comedy|Drama', 24, 25, '9/9/2021', 7.02);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (19, 'The Little Kidnappers', 'Tobe Southam', 'Drama|Romance|War', 15, 23, '10/23/2002', 33.66);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (9, 'Mr. Lucky', 'Woodie Seath', 'Comedy|Romance', 19, 20, '1/16/2002', 65.82);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (10, 'Manitou, The', 'Hodge Blackey', 'Horror', 34, 24, '1/27/2019', 145.1);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (98, 'Rent-A-Cop', 'Patton Cockland', 'Action|Comedy|Crime', 4, 23, '6/6/2017', 9.85);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (19, 'American Yakuza', 'Leroy Ferrie', 'Action|Drama|Thriller', 25, 14, '6/2/2003', 72.48);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (75, 'Malice N Wonderland', 'Brandea Lockhurst', 'Drama|Musical', 33, 13, '6/6/2016', 37.69);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (48, 'Good Year, A', 'Lynnea Palia', 'Comedy|Drama|Romance', 36, 24, '11/15/2007', null);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (4, 'The Suspended Step of the Stork', 'Stearn Jakubovsky', 'Drama|Romance', 45, 7, '12/12/2010', 145.36);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (19, 'Nobody''s Children (I figli di nessuno)', 'Candie Iianon', 'Drama|Romance', 29, 12, '3/9/2020', 24.72);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (75, 'Injury to One, An', 'Jeremy Hawson', 'Documentary', 6, 8, '11/16/2017', null);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (50, 'Shoppen ', 'Laure Gullen', 'Comedy|Romance', 27, 11, '4/3/2011', 18.94);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (77, 'Young Americans, The', 'Clareta Llewellyn', 'Crime|Drama', 24, 18, '10/25/2010', 140.77);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (54, 'Act of Aggression', 'Jacquie Cronkshaw', 'Crime|Drama', 50, 1, '8/25/2016', 93.06);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (95, 'Alien Raiders', 'Kiley Liddyard', 'Mystery|Sci-Fi|Thriller', 23, 2, '12/30/2010', 70.72);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (72, 'Halloween: The Curse of Michael Myers (Halloween 6: The Curse of Michael Myers)', 'Isahella Janek', 'Horror|Thriller', 19, 18, '7/14/2013', 43.21);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (91, 'Ink', 'Camel Dawltrey', 'Action|Fantasy|Sci-Fi', 40, 7, '2/29/2012', 23.95);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (82, 'From Above', 'Gwenni Wickett', 'Drama|Romance', 41, 14, '8/17/2022', 32.21);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (87, '7th Floor', 'Lari Jennens', 'Mystery|Thriller', 46, 16, '2/16/2004', null);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (95, 'Forgiving Dr. Mengele', 'Thedrick Templman', 'Documentary', 35, 23, '10/28/2020', null);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (26, 'Raincoat', 'Lynne Melladew', 'Drama|Romance', 42, 15, '11/12/2000', 95.81);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (3, 'The Returned', 'Derby Pinnock', 'Drama|Horror|Thriller', 30, 23, '7/7/2018', 8.83);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (99, 'Superman/Batman: Apocalypse', 'Jaquenetta Gostridge', 'Animation', 50, 20, '10/26/2003', 108.37);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (14, 'Tomorrow at Dawn (Demain dès l''aube)', 'Launce Botte', 'Drama', 24, 17, '6/18/2015', 130.43);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (64, 'Hard Times', 'Gae Korneluk', 'Action|Drama', 37, 25, '1/1/2019', 63.78);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (20, 'Dragon Ball Z: Dead Zone (Doragon bôru Z 1: Ora no Gohan wo kaese)', 'Aland Giraudou', 'Action|Adventure|Animation|Fantasy|Sci-Fi', 16, 11, '6/3/2017', null);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (98, 'Dollman', 'Joshua MacDiarmid', 'Action|Comedy|Crime', 46, 18, '6/4/2002', 75.18);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (58, 'Final Destination, The (Final Destination 4) (Final Destination in 3-D, The)', 'Pauly Ayshford', 'Horror|Thriller', 40, 16, '8/5/2023', 43.77);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (11, 'Negotiator, The', 'Roanna Gavriel', 'Action|Crime|Drama|Mystery|Thriller', 40, 24, '8/25/2013', 20.81);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (27, 'Christmas Carol, A (Scrooge)', 'Hansiain Krinks', 'Drama|Fantasy', 33, 11, '5/28/2002', 60.28);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (83, 'Lady, The', 'Ki Akitt', 'Drama', 48, 21, '8/19/2021', 120.54);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (64, 'Princess Aurora (Orora gongju)', 'Debby Nuth', 'Crime|Drama|Mystery', 44, 25, '2/20/2017', 100.46);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (60, 'Into the West', 'Benni Wiffield', 'Adventure|Drama|Western', 39, 21, '9/4/2019', 109.81);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (42, 'Carnage', 'Lucius Mottini', 'Comedy|Drama', 37, 5, '7/13/2023', 30.27);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (60, 'Pure Country', 'Tarrah Bozier', 'Drama|Musical|Romance', 15, 8, '4/6/2017', 7.19);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (23, 'Battlefield Earth', 'Flin Shakespeare', 'Action|Sci-Fi', 25, 11, '4/1/2023', 50.51);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (82, 'Zatoichi', 'Ozzie Novik', 'Action|Drama', 4, 3, '2/17/2008', 144.18);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (73, 'Whistling in the Dark', 'Mary Leed', 'Comedy|Mystery', 26, 10, '4/2/2013', 100.12);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (86, 'Love''s Kitchen', 'Natalina Josephy', 'Comedy|Drama|Romance', 41, 13, '7/12/2007', 96.68);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (22, 'Chicks with Sticks', 'Rhodia Alenikov', 'Comedy|Drama', 3, 2, '9/6/2020', 59.2);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (93, 'Son of Dracula', 'Ellette Sawl', 'Horror', 41, 17, '3/7/2014', 27.61);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (14, 'Down Twisted', 'Abdul Hardiker', 'Action|Adventure|Crime|Drama|Thriller', 47, 12, '6/7/2006', null);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (39, 'Distance', 'Ulric Mingardi', 'Drama', 36, 22, '9/26/2020', 62.02);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (27, 'Girl in the Red Velvet Swing, The', 'Marcellus Dronsfield', 'Crime|Drama|Romance', 34, 22, '12/12/2018', 38.63);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (63, 'Getaway, The', 'Carrie Talks', 'Action|Crime|Drama|Thriller', 5, 5, '2/12/2004', 44.65);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (70, 'The Valley of Gwangi', 'Sergent Ulyatt', 'Sci-Fi|Thriller|Western', 7, 6, '11/20/2007', 105.57);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (28, 'Dahmer', 'Aurelea Vinton', 'Drama|Horror|Thriller', 5, 17, '10/6/2009', 50.55);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (15, 'Background to Danger', 'Bellanca Sheerin', 'Drama|Thriller|War', 17, 21, '5/9/2007', 34.05);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (30, 'Teen Wolf Too', 'Alexine Tierney', 'Comedy', 24, 15, '6/21/2009', 103.0);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (65, 'Valiant', 'Gerik Bromley', 'Adventure|Animation|Children|Comedy|Fantasy|War', 14, 7, '6/23/2004', 125.76);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (30, 'Easy Rider', 'Spike Hearnaman', 'Adventure|Drama', 49, 21, '6/12/2016', 1.35);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (27, 'House of Wax', 'Karlik Diwell', 'Crime|Horror|Mystery|Thriller', 48, 23, '10/29/2018', 107.47);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (61, 'Godzilla''s Revenge (Gojira-Minira-Gabara: Oru Kaijû Daishingeki) (All Monsters Attack)', 'Clement Lusgdin', 'Children', 7, 0, '11/5/2014', 30.14);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (13, 'Steel', 'Ax Fentem', 'Action', 21, 17, '9/20/2002', 24.52);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (34, '13', 'Flore Flescher', 'Thriller', 31, 21, '1/26/2017', 103.81);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (63, 'Life is a Miracle (Zivot je cudo)', 'Adolph Weatherall', 'Comedy|Drama|Musical|Romance|War', 27, 4, '10/5/2004', 14.36);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (99, 'Adam and Eve (Adão e Eva)', 'Thalia Giorio', 'Drama', 33, 16, '11/17/2018', 100.5);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (70, 'Cape No. 7 (Hái-kak chhit-ho)', 'Adah Bernardet', 'Comedy|Drama|Romance', 17, 18, '12/12/2001', 147.3);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (29, 'Ghosts of the Abyss', 'Arie Bountiff', 'Documentary|IMAX', 46, 0, '8/5/2021', 74.14);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (19, 'Cloudburst', 'Lotti Rumens', 'Adventure|Comedy|Drama', 39, 9, '12/3/2021', 97.73);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (19, 'Gabriel Over the White House', 'Arni Hultberg', 'Drama|Fantasy|Romance', 8, 21, '7/8/2022', 142.54);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (41, 'Last Passenger', 'Alayne Frampton', 'Action|Mystery|Thriller', 43, 22, '8/16/2012', 27.13);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (28, 'Tentacles (Tentacoli)', 'Lonnie Krzyzaniak', 'Horror|Sci-Fi|Thriller', 36, 23, '10/26/2001', 26.46);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (48, 'Rare Birds', 'Kane Winchcomb', 'Comedy|Drama', 24, 18, '2/24/2017', 6.73);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (92, 'Feds', 'Pedro Freire', 'Comedy', 22, 0, '2/17/2008', 112.68);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (49, 'Thirst', 'Hilda Dowsett', 'Drama', 10, 6, '7/25/2022', 23.91);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (66, 'Planet of the Vampires (Terrore nello spazio)', 'Lyn Abella', 'Horror|Sci-Fi', 42, 23, '10/11/2018', 39.87);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (57, 'Blue State', 'Rustie McLaverty', 'Comedy', 12, 4, '1/1/2017', null);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (55, 'Reaping, The', 'Elden Marciskewski', 'Horror|Thriller', 12, 4, '1/2/2011', 34.73);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (78, 'Unspeakable Act, The', 'Franchot D''Abbot-Doyle', 'Drama', 36, 18, '6/8/2016', 103.72);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (23, 'Osaka Elegy (Naniwa erejî)', 'Evangelia Danton', 'Drama', 2, 8, '4/12/2021', 109.96);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (51, 'Godzilla vs. SpaceGodzilla (Gojira VS Supesugojira)', 'Janey Johanssen', 'Action|Sci-Fi', 26, 23, '7/5/2013', 121.84);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (70, 'Guitar, The', 'Berenice Willingam', 'Drama|Romance', 11, 8, '11/5/2009', 140.31);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (24, 'The Lazarus Effect', 'Adrian Trevance', 'Horror|Thriller', 7, 18, '11/24/2018', 88.86);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (96, 'Attack of the 50 Foot Woman', 'Imogen Lake', 'Comedy|Sci-Fi', 34, 7, '2/5/2001', 121.74);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (92, 'Loose Change 9/11: An American Coup', 'Chico McGrory', 'Documentary', 25, 4, '11/13/2002', 85.67);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (13, 'She Monkeys', 'Rubetta Cleveland', 'Drama', 39, 17, '10/17/2021', null);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (49, 'Things We Lost in the Fire', 'Merralee Duplock', 'Drama|Romance', 13, 16, '7/14/2001', 113.4);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (62, 'Frenzy', 'Dianna Petrello', 'Thriller', 15, 18, '11/29/2000', 143.86);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (100, 'Lost in America', 'Jorge Fridd', 'Comedy', 22, 1, '3/30/2016', 39.36);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (29, 'Manufactured Landscapes', 'Jobye Pollins', 'Documentary', 28, 13, '5/3/2006', 109.68);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (14, 'Cat Soup (Nekojiru-so)', 'Xaviera Bisterfeld', 'Adventure|Animation|Drama|Horror', 34, 0, '11/6/2008', 109.37);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (87, 'Invasion of the Body Snatchers', 'Brig Mantrup', 'Horror|Mystery|Sci-Fi|Thriller', 10, 16, '1/29/2011', 75.11);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (58, 'I''ve Loved You So Long (Il y a longtemps que je t''aime)', 'Marilyn Jandel', 'Drama|Mystery', 9, 1, '8/6/2007', null);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (95, 'Angel', 'Langsdon Cluse', 'Action|Crime|Thriller', 17, 24, '4/15/2005', 42.86);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (14, 'Khroustaliov, My Car! (Khrustalyov, mashinu!)', 'Silvio Egalton', 'Comedy|Drama', 23, 7, '9/8/2009', 89.77);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (18, 'Parent Trap, The', 'Jed Lamberton', 'Children|Comedy|Romance', 33, 19, '9/11/2007', 142.52);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (4, 'Terminator 3: Rise of the Machines', 'Emmerich Bowskill', 'Action|Adventure|Sci-Fi', 6, 1, '5/5/2001', 46.83);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (8, 'Line of Sight', 'Hinda Letchford', 'Documentary', 32, 13, '1/22/2022', 38.84);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (33, 'Not for or Against (Quite the Contrary) (Ni pour, ni contre (bien au contraire))', 'Skylar Stapels', 'Crime|Drama', 11, 12, '7/27/2001', null);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (99, 'Boy on a Dolphin', 'Doy Dinesen', 'Adventure|Romance', 7, 17, '7/14/2019', 81.44);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (90, 'Third Miracle, The', 'Rickard Darycott', 'Drama', 40, 13, '7/15/2006', 53.62);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (99, 'Adrenaline Drive (Adorenarin doraibu)', 'Wilmer Chasteney', 'Comedy', 14, 3, '3/31/2014', 139.84);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (11, 'Kidnap Syndicate', 'Rozelle McGrill', 'Crime', 33, 20, '1/19/2010', 4.43);
insert into book (id, book_title, author, genre, total_copies, available_copies, date_acquired, price) values (99, 'Point, The', 'Reuven Jillis', 'Animation|Children|Fantasy|Musical', 40, 8, '1/21/2003', 31.49);
